export default function Head() {
  return (
    <>
      <title>Note Down</title>
      <meta name="description" content="Generated by create-t3-app" />
      <link rel="icon" href="/favicon.ico" />
    </>
  );
}
